-- MySQL Script generated by MySQL Workbench
-- Sat Aug 18 01:52:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zavrsni
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zavrsni` ;

-- -----------------------------------------------------
-- Schema zavrsni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zavrsni` DEFAULT CHARACTER SET utf8 ;
USE `zavrsni` ;

-- -----------------------------------------------------
-- Table `zavrsni`.`korisnik_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni`.`korisnik_status` ;

CREATE TABLE IF NOT EXISTS `zavrsni`.`korisnik_status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni`.`marke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni`.`marke` ;

CREATE TABLE IF NOT EXISTS `zavrsni`.`marke` (
  `id_marke` INT NOT NULL AUTO_INCREMENT,
  `marke` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marke`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni`.`stanje_vozila`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni`.`stanje_vozila` ;

CREATE TABLE IF NOT EXISTS `zavrsni`.`stanje_vozila` (
  `id_stanje_vozila` INT NOT NULL AUTO_INCREMENT,
  `stanje_vozila` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_stanje_vozila`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni`.`gorivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni`.`gorivo` ;

CREATE TABLE IF NOT EXISTS `zavrsni`.`gorivo` (
  `id_gorivo` INT NOT NULL AUTO_INCREMENT,
  `gorivo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gorivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `zavrsni`.`korisnik` (
  `id_korisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `poslednje_logovanje` DATETIME NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_korisnik`),
  INDEX `fk_korisnik_korisnik_status1_idx` (`id_status` ASC),
  CONSTRAINT `fk_korisnik_korisnik_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `zavrsni`.`korisnik_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni`.`oglas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni`.`oglas` ;

CREATE TABLE IF NOT EXISTS `zavrsni`.`oglas` (
  `id_oglas` INT NOT NULL AUTO_INCREMENT,
  `id_marke` INT NOT NULL,
  `id_stanje_vozila` INT NOT NULL,
  `id_gorivo` INT NOT NULL,
  `godiste` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  `kontakt` VARCHAR(45) NOT NULL,
  `kilometraza` INT NOT NULL,
  `slika_oglasa` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(200) NOT NULL,
  `id_korisnik` INT NOT NULL,
  PRIMARY KEY (`id_oglas`),
  INDEX `fk_oglas_marke1_idx` (`id_marke` ASC),
  INDEX `fk_oglas_stanje_vozila1_idx` (`id_stanje_vozila` ASC),
  INDEX `fk_oglas_gorivo1_idx` (`id_gorivo` ASC),
  INDEX `fk_oglas_korisnik1_idx` (`id_korisnik` ASC),
  CONSTRAINT `fk_oglas_marke1`
    FOREIGN KEY (`id_marke`)
    REFERENCES `zavrsni`.`marke` (`id_marke`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oglas_stanje_vozila1`
    FOREIGN KEY (`id_stanje_vozila`)
    REFERENCES `zavrsni`.`stanje_vozila` (`id_stanje_vozila`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oglas_gorivo1`
    FOREIGN KEY (`id_gorivo`)
    REFERENCES `zavrsni`.`gorivo` (`id_gorivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oglas_korisnik1`
    FOREIGN KEY (`id_korisnik`)
    REFERENCES `zavrsni`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
